// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBximwEWBiOQJE2MzQZ0dc41ZQEnRj8fyg',
    appId: '1:597783812660:web:75d4deeb9ac7c284990861',
    messagingSenderId: '597783812660',
    projectId: 'migla-app',
    authDomain: 'migla-app.firebaseapp.com',
    storageBucket: 'migla-app.firebasestorage.app',
    measurementId: 'G-YWEY8P04QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_DLIWZ_9oiA6mIaNvuQF-LkeCy1Pqua0',
    appId: '1:597783812660:android:bc4fc4282e2b46ee990861',
    messagingSenderId: '597783812660',
    projectId: 'migla-app',
    storageBucket: 'migla-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9LQ74BuVjcYHDIs1DISaGp0KzWbHTnGg',
    appId: '1:597783812660:ios:d18397151491655c990861',
    messagingSenderId: '597783812660',
    projectId: 'migla-app',
    storageBucket: 'migla-app.firebasestorage.app',
    iosBundleId: 'com.migla.miglaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9LQ74BuVjcYHDIs1DISaGp0KzWbHTnGg',
    appId: '1:597783812660:ios:d18397151491655c990861',
    messagingSenderId: '597783812660',
    projectId: 'migla-app',
    storageBucket: 'migla-app.firebasestorage.app',
    iosBundleId: 'com.migla.miglaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBximwEWBiOQJE2MzQZ0dc41ZQEnRj8fyg',
    appId: '1:597783812660:web:febd66b9ba1e9073990861',
    messagingSenderId: '597783812660',
    projectId: 'migla-app',
    authDomain: 'migla-app.firebaseapp.com',
    storageBucket: 'migla-app.firebasestorage.app',
    measurementId: 'G-F7ZPVXGH0L',
  );
}
